export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const SHOW_ABOUT_MODAL = 'SHOW_ABOUT_MODAL';
export const HIDE_ABOUT_MODAL = 'HIDE_ABOUT_MODAL';
export const SHOW_REGISTER_MODAL = 'SHOW_REGISTER_MODAL';
export const HIDE_REGISTER_MODAL = 'HIDE_REGISTER_MODAL';
